version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017
    volumes:
      - /mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nhanpq
      MONGO_INITDB_ROOT_PASSWORD: abc123